# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/class/classes/jtan127/final-project-rkand011-lcano014-jtan127-rdiaz082

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/class/classes/jtan127/final-project-rkand011-lcano014-jtan127-rdiaz082

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/class/classes/jtan127/final-project-rkand011-lcano014-jtan127-rdiaz082/CMakeFiles /data/class/classes/jtan127/final-project-rkand011-lcano014-jtan127-rdiaz082//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/class/classes/jtan127/final-project-rkand011-lcano014-jtan127-rdiaz082/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named runAllTest

# Build rule for target.
runAllTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runAllTest
.PHONY : runAllTest

# fast build rule for target.
runAllTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/build
.PHONY : runAllTest/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/Character.o: src/Character.cpp.o
.PHONY : src/Character.o

# target to build an object file
src/Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Character.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/Character.cpp.o
.PHONY : src/Character.cpp.o

src/Character.i: src/Character.cpp.i
.PHONY : src/Character.i

# target to preprocess a source file
src/Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Character.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/Character.cpp.i
.PHONY : src/Character.cpp.i

src/Character.s: src/Character.cpp.s
.PHONY : src/Character.s

# target to generate assembly for a file
src/Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Character.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/Character.cpp.s
.PHONY : src/Character.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Game.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Game.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Game.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/SlowTyping.o: src/SlowTyping.cpp.o
.PHONY : src/SlowTyping.o

# target to build an object file
src/SlowTyping.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SlowTyping.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/SlowTyping.cpp.o
.PHONY : src/SlowTyping.cpp.o

src/SlowTyping.i: src/SlowTyping.cpp.i
.PHONY : src/SlowTyping.i

# target to preprocess a source file
src/SlowTyping.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SlowTyping.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/SlowTyping.cpp.i
.PHONY : src/SlowTyping.cpp.i

src/SlowTyping.s: src/SlowTyping.cpp.s
.PHONY : src/SlowTyping.s

# target to generate assembly for a file
src/SlowTyping.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SlowTyping.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/SlowTyping.cpp.s
.PHONY : src/SlowTyping.cpp.s

src/UCI.o: src/UCI.cpp.o
.PHONY : src/UCI.o

# target to build an object file
src/UCI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCI.cpp.o
.PHONY : src/UCI.cpp.o

src/UCI.i: src/UCI.cpp.i
.PHONY : src/UCI.i

# target to preprocess a source file
src/UCI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCI.cpp.i
.PHONY : src/UCI.cpp.i

src/UCI.s: src/UCI.cpp.s
.PHONY : src/UCI.s

# target to generate assembly for a file
src/UCI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCI.cpp.s
.PHONY : src/UCI.cpp.s

src/UCLA.o: src/UCLA.cpp.o
.PHONY : src/UCLA.o

# target to build an object file
src/UCLA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCLA.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCLA.cpp.o
.PHONY : src/UCLA.cpp.o

src/UCLA.i: src/UCLA.cpp.i
.PHONY : src/UCLA.i

# target to preprocess a source file
src/UCLA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCLA.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCLA.cpp.i
.PHONY : src/UCLA.cpp.i

src/UCLA.s: src/UCLA.cpp.s
.PHONY : src/UCLA.s

# target to generate assembly for a file
src/UCLA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCLA.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCLA.cpp.s
.PHONY : src/UCLA.cpp.s

src/UCR.o: src/UCR.cpp.o
.PHONY : src/UCR.o

# target to build an object file
src/UCR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCR.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCR.cpp.o
.PHONY : src/UCR.cpp.o

src/UCR.i: src/UCR.cpp.i
.PHONY : src/UCR.i

# target to preprocess a source file
src/UCR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCR.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCR.cpp.i
.PHONY : src/UCR.cpp.i

src/UCR.s: src/UCR.cpp.s
.PHONY : src/UCR.s

# target to generate assembly for a file
src/UCR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCR.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCR.cpp.s
.PHONY : src/UCR.cpp.s

src/UCSB.o: src/UCSB.cpp.o
.PHONY : src/UCSB.o

# target to build an object file
src/UCSB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCSB.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCSB.cpp.o
.PHONY : src/UCSB.cpp.o

src/UCSB.i: src/UCSB.cpp.i
.PHONY : src/UCSB.i

# target to preprocess a source file
src/UCSB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCSB.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCSB.cpp.i
.PHONY : src/UCSB.cpp.i

src/UCSB.s: src/UCSB.cpp.s
.PHONY : src/UCSB.s

# target to generate assembly for a file
src/UCSB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCSB.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCSB.cpp.s
.PHONY : src/UCSB.cpp.s

src/UCSD.o: src/UCSD.cpp.o
.PHONY : src/UCSD.o

# target to build an object file
src/UCSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCSD.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCSD.cpp.o
.PHONY : src/UCSD.cpp.o

src/UCSD.i: src/UCSD.cpp.i
.PHONY : src/UCSD.i

# target to preprocess a source file
src/UCSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCSD.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCSD.cpp.i
.PHONY : src/UCSD.cpp.i

src/UCSD.s: src/UCSD.cpp.s
.PHONY : src/UCSD.s

# target to generate assembly for a file
src/UCSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/UCSD.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/src/UCSD.cpp.s
.PHONY : src/UCSD.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/GameTest.o: tests/GameTest.cpp.o
.PHONY : tests/GameTest.o

# target to build an object file
tests/GameTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/GameTest.cpp.o
.PHONY : tests/GameTest.cpp.o

tests/GameTest.i: tests/GameTest.cpp.i
.PHONY : tests/GameTest.i

# target to preprocess a source file
tests/GameTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/GameTest.cpp.i
.PHONY : tests/GameTest.cpp.i

tests/GameTest.s: tests/GameTest.cpp.s
.PHONY : tests/GameTest.s

# target to generate assembly for a file
tests/GameTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/GameTest.cpp.s
.PHONY : tests/GameTest.cpp.s

tests/SlowTypingTest.o: tests/SlowTypingTest.cpp.o
.PHONY : tests/SlowTypingTest.o

# target to build an object file
tests/SlowTypingTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/SlowTypingTest.cpp.o
.PHONY : tests/SlowTypingTest.cpp.o

tests/SlowTypingTest.i: tests/SlowTypingTest.cpp.i
.PHONY : tests/SlowTypingTest.i

# target to preprocess a source file
tests/SlowTypingTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/SlowTypingTest.cpp.i
.PHONY : tests/SlowTypingTest.cpp.i

tests/SlowTypingTest.s: tests/SlowTypingTest.cpp.s
.PHONY : tests/SlowTypingTest.s

# target to generate assembly for a file
tests/SlowTypingTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/SlowTypingTest.cpp.s
.PHONY : tests/SlowTypingTest.cpp.s

tests/UCITest.o: tests/UCITest.cpp.o
.PHONY : tests/UCITest.o

# target to build an object file
tests/UCITest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCITest.cpp.o
.PHONY : tests/UCITest.cpp.o

tests/UCITest.i: tests/UCITest.cpp.i
.PHONY : tests/UCITest.i

# target to preprocess a source file
tests/UCITest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCITest.cpp.i
.PHONY : tests/UCITest.cpp.i

tests/UCITest.s: tests/UCITest.cpp.s
.PHONY : tests/UCITest.s

# target to generate assembly for a file
tests/UCITest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCITest.cpp.s
.PHONY : tests/UCITest.cpp.s

tests/UCLAtest.o: tests/UCLAtest.cpp.o
.PHONY : tests/UCLAtest.o

# target to build an object file
tests/UCLAtest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCLAtest.cpp.o
.PHONY : tests/UCLAtest.cpp.o

tests/UCLAtest.i: tests/UCLAtest.cpp.i
.PHONY : tests/UCLAtest.i

# target to preprocess a source file
tests/UCLAtest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCLAtest.cpp.i
.PHONY : tests/UCLAtest.cpp.i

tests/UCLAtest.s: tests/UCLAtest.cpp.s
.PHONY : tests/UCLAtest.s

# target to generate assembly for a file
tests/UCLAtest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCLAtest.cpp.s
.PHONY : tests/UCLAtest.cpp.s

tests/UCRTest.o: tests/UCRTest.cpp.o
.PHONY : tests/UCRTest.o

# target to build an object file
tests/UCRTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCRTest.cpp.o
.PHONY : tests/UCRTest.cpp.o

tests/UCRTest.i: tests/UCRTest.cpp.i
.PHONY : tests/UCRTest.i

# target to preprocess a source file
tests/UCRTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCRTest.cpp.i
.PHONY : tests/UCRTest.cpp.i

tests/UCRTest.s: tests/UCRTest.cpp.s
.PHONY : tests/UCRTest.s

# target to generate assembly for a file
tests/UCRTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCRTest.cpp.s
.PHONY : tests/UCRTest.cpp.s

tests/UCSBTest.o: tests/UCSBTest.cpp.o
.PHONY : tests/UCSBTest.o

# target to build an object file
tests/UCSBTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCSBTest.cpp.o
.PHONY : tests/UCSBTest.cpp.o

tests/UCSBTest.i: tests/UCSBTest.cpp.i
.PHONY : tests/UCSBTest.i

# target to preprocess a source file
tests/UCSBTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCSBTest.cpp.i
.PHONY : tests/UCSBTest.cpp.i

tests/UCSBTest.s: tests/UCSBTest.cpp.s
.PHONY : tests/UCSBTest.s

# target to generate assembly for a file
tests/UCSBTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCSBTest.cpp.s
.PHONY : tests/UCSBTest.cpp.s

tests/UCSDtest.o: tests/UCSDtest.cpp.o
.PHONY : tests/UCSDtest.o

# target to build an object file
tests/UCSDtest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCSDtest.cpp.o
.PHONY : tests/UCSDtest.cpp.o

tests/UCSDtest.i: tests/UCSDtest.cpp.i
.PHONY : tests/UCSDtest.i

# target to preprocess a source file
tests/UCSDtest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCSDtest.cpp.i
.PHONY : tests/UCSDtest.cpp.i

tests/UCSDtest.s: tests/UCSDtest.cpp.s
.PHONY : tests/UCSDtest.s

# target to generate assembly for a file
tests/UCSDtest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runAllTest.dir/build.make CMakeFiles/runAllTest.dir/tests/UCSDtest.cpp.s
.PHONY : tests/UCSDtest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... main"
	@echo "... runAllTest"
	@echo "... src/Character.o"
	@echo "... src/Character.i"
	@echo "... src/Character.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/SlowTyping.o"
	@echo "... src/SlowTyping.i"
	@echo "... src/SlowTyping.s"
	@echo "... src/UCI.o"
	@echo "... src/UCI.i"
	@echo "... src/UCI.s"
	@echo "... src/UCLA.o"
	@echo "... src/UCLA.i"
	@echo "... src/UCLA.s"
	@echo "... src/UCR.o"
	@echo "... src/UCR.i"
	@echo "... src/UCR.s"
	@echo "... src/UCSB.o"
	@echo "... src/UCSB.i"
	@echo "... src/UCSB.s"
	@echo "... src/UCSD.o"
	@echo "... src/UCSD.i"
	@echo "... src/UCSD.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/GameTest.o"
	@echo "... tests/GameTest.i"
	@echo "... tests/GameTest.s"
	@echo "... tests/SlowTypingTest.o"
	@echo "... tests/SlowTypingTest.i"
	@echo "... tests/SlowTypingTest.s"
	@echo "... tests/UCITest.o"
	@echo "... tests/UCITest.i"
	@echo "... tests/UCITest.s"
	@echo "... tests/UCLAtest.o"
	@echo "... tests/UCLAtest.i"
	@echo "... tests/UCLAtest.s"
	@echo "... tests/UCRTest.o"
	@echo "... tests/UCRTest.i"
	@echo "... tests/UCRTest.s"
	@echo "... tests/UCSBTest.o"
	@echo "... tests/UCSBTest.i"
	@echo "... tests/UCSBTest.s"
	@echo "... tests/UCSDtest.o"
	@echo "... tests/UCSDtest.i"
	@echo "... tests/UCSDtest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

